apiVersion: v1
kind: Service
metadata:
  name: ai-gateway
  namespace: fsi-ai-gateway-maas
  labels:
    app: ai-gateway
spec:
  selector:
    app: ai-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ai-gateway
  namespace: fsi-ai-gateway-maas
  labels:
    app: ai-gateway
spec:
  to:
    kind: Service
    name: ai-gateway
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
